CREATE DATABASE TicketsList;
USE TicketsList;
DROP TABLE IF EXISTS `TICKETS_DATA`;
CREATE TABLE `TICKETS_DATA` (
  `TICKET_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TICKET_DATE` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`TICKET_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10330929 DEFAULT CHARSET=utf8mb4;

